name: AVA Reload
on:
  push:
    branches: [main]
  schedule:
    - cron: '*/50 * * * *'
jobs:
  issue:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: wget https://cheatgame.pro/education/dataairdrop/dataava.txt; python ava_reload.py
